import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import styles from '../styles/myStyle.module.css'
import Card from 'components/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.mainContainer}>
        <div className={styles.navbar}>
          <img className={styles.logo} src='https://www.feba.co.in/static/media/logo.9f98b1b6.png'/>
          <text className={styles.logoName}>Feba</text>
        </div>
        <div className={styles.filters}>
          <div className={styles.cityWrapper}>
            <select className={styles.cities}>
              <option>Amritsar</option>
              <option>Bangalore</option>
              <option>Chandigarh</option>
              <option>Chennai</option>
              <option>Delhi-NCR</option>
              <option>Hyderabad</option>
              <option>Jaipur</option>
              <option>Jalandhar</option>
              <option>Kolkata</option>
              <option>Lucknow</option>
            </select>
          </div>
          <div className={styles.servicesWrapper}>
            <select className={styles.cities}>
              <option>Wedding Services</option>
              <option>Cakes</option>
              <option>Catering</option>
              <option>DJ</option>
              <option>Decorators</option>
              <option>Venue</option>
              <option>Wedding Entertaninment</option>
              <option>Mehandi Artist</option>
              <option>Photographer</option>
              <option>Sangeet Choreographers</option>
              <option>Food Stalls</option>
            </select>
          </div>
          <div className={styles.filtersWrapper}>
          <svg className={styles.setting}><path d="M3 17v2h6v-2H3zM3 5v2h10V5H3zm10 16v-2h8v-2h-8v-2h-2v6h2zM7 9v2H3v2h4v2h2V9H7zm14 4v-2H11v2h10zm-6-4h2V7h4V5h-4V3h-2v6z"></path></svg>
            <span>            
            Filters</span>
          </div>

        </div>
        <div className={styles.imgSec}>
          <Card 
            path="https://www.feba.co.in/media/BridalImages/3616/123/16522530747630.jpg"
            city="Mumbai, Lower Parel"
            rating="4.8"
            name="The St. Regis"
            price="3800"
            />
          <Card 
            path="https://www.feba.co.in/media/BridalImages/323/123/16266912445950.jpg"
            city="Chandigarh, Mohali"
            rating="4.8"
            name="Hair Game By Priyanka"
            price="15000"
            />
          <Card 
            path="https://www.feba.co.in/media/BridalImages/459/123/16457970553300.jpg"
            city="Pune, Kalyani Nagar"
            rating="4.8"
            name="S R Makeovers"
            price="12000"
            />
          <Card 
            path="https://www.feba.co.in/media/BridalImages/330/123/16400773428020.jpg"
            city="Delhi-NCR"
            rating="4.8"
            name="Eshita's Makeovers"
            price="20000"
            />
          <Card 
            path="https://www.feba.co.in/media/BridalImages/290/123/15951540232520.jpg"
            city="Nagpur"
            rating="4.8"
            name="Sara_Makeovers_"
            price="13000"
            />
          <Card 
            path="https://www.feba.co.in/media/BridalImages/5665/123/16522464305160.jpg"
            city="Mumbai, South Mumbai"
            rating="4.8"
            name="Neel-Tote on Turf"
            price="2400"
            />
          <Card 
            path="https://www.feba.co.in/media/BridalImages/280/123/16605538955660.jpg"
            city="Mumbai, Bandra"
            rating="4.8"
            name="Makeup By Sneha Sk"
            price="20000"
            />
          <Card 
            path="https://www.feba.co.in/media/BridalImages/312/123/15982713863821.jpg"
            city="Lucknow"
            rating="4.8"
            name="The beauty Poetry"
            price="14500"
            />
        </div>
      </main>
    </>
  )
}
